use sql1;
-- Write a query to display all patient records.
SELECT *
FROM report;

-- Write a query to display only patient name, gender, age, department, and doctor.
SELECT Patient_Name,
       Gender,
       Age,
       Department,
       Doctor
FROM report;

-- Write a query to display patients older than 60 years.
SELECT Patient_Name,
       Age,
       Department
FROM report
WHERE Age>60;

-- Write a query to count the total number of patients.
SELECT COUNT(*) AS Total_Patients
FROM report;

-- Write a query to find the average age of patients.
SELECT AVG(Age) AS Average_Age
FROM report;

-- Write a query to find the highest treatment cost
SELECT MAX(Treatment_Cost) AS Highest_Cost
FROM report;

-- Write a query to display the top 10 most expensive treatments
SELECT Patient_Name,
       Treatment,
       Treatment_Cost
FROM report
ORDER BY Treatment_Cost DESC
LIMIT 10;

-- Write a query to count patients department-wise.
SELECT Department,
       COUNT(*) AS Total_Patients
FROM report
GROUP BY Department
ORDER BY Total_Patients DESC;

-- Write a query to calculate the total revenue generated by each department.
SELECT Department,
       SUM(Treatment_Cost) AS Revenue
FROM report
GROUP BY Department
ORDER BY Revenue DESC;

-- Write a query to find the average treatment cost for each department.
SELECT Department,
       ROUND(AVG(Treatment_Cost),2) AS Average_Cost
FROM report
GROUP BY Department;

-- Write a query to find doctors who treated more than 100 patients.
SELECT Doctor,
       COUNT(*) AS Patients_Treated
FROM report
GROUP BY Doctor
HAVING COUNT(*)>100;

-- Write a query to display the number of patients by payment status.
SELECT Payment_Status,
       COUNT(*) AS Total
FROM report
GROUP BY Payment_Status;

-- Write a query to find patients whose treatment cost is greater than the average treatment cost.
SELECT Patient_Name,
       Treatment_Cost
FROM report
WHERE Treatment_Cost >
(
SELECT AVG(Treatment_Cost)
FROM report
);

-- Write a query to display the number of patients admitted in each month.
SELECT MONTH(Admission_Date) AS Month_No,
       COUNT(*) AS Total_Admissions
FROM report
GROUP BY MONTH(Admission_Date)
ORDER BY Month_No;

-- Write a query to rank patients based on treatment cost using the RANK() window function.
SELECT Patient_Name,
       Treatment_Cost,
       RANK() OVER(ORDER BY Treatment_Cost DESC) AS Cost_Rank
FROM report;

-- Write a query to assign row numbers to patients within each department.
SELECT Department,
       Patient_Name,
       ROW_NUMBER() OVER(PARTITION BY Department ORDER BY Treatment_Cost DESC) AS Row_Num
FROM report;

-- Write a query to find the second highest treatment cost.
SELECT MAX(Treatment_Cost) AS Second_Highest
FROM report
WHERE Treatment_Cost <
(
SELECT MAX(Treatment_Cost)
FROM report
);

-- Write a query to calculate the cumulative treatment cost department-wise.
SELECT Department,
       Patient_Name,
       Treatment_Cost,
       SUM(Treatment_Cost)
       OVER(PARTITION BY Department
            ORDER BY Treatment_Cost) AS Running_Total
FROM report;

-- Write a query to classify patients into age groups using the CASE statement.
SELECT Patient_Name,
       Age,
       CASE
            WHEN Age<18 THEN 'Child'
            WHEN Age BETWEEN 18 AND 40 THEN 'Young Adult'
            WHEN Age BETWEEN 41 AND 60 THEN 'Adult'
            ELSE 'Senior Citizen'
       END AS Age_Group
FROM report;

-- Write a query to find the doctor generating the highest treatment revenue.
SELECT Doctor,
       SUM(Treatment_Cost) AS Revenue
FROM report
GROUP BY Doctor
ORDER BY Revenue DESC
LIMIT 1;

-- Write a query using a Common Table Expression (CTE) to find departments whose average treatment cost is greater than ₹50,000.
 WITH DeptCost AS
(
SELECT Department,
       AVG(Treatment_Cost) AS Avg_Cost
FROM report
GROUP BY Department
)
SELECT *
FROM DeptCost
WHERE Avg_Cost>50000;

-- Write a query to find the top three highest treatment costs in each department using DENSE_RANK().
WITH RankedPatients AS
(
SELECT Department,
       Patient_Name,
       Treatment_Cost,
       DENSE_RANK() OVER
       (
       PARTITION BY Department
       ORDER BY Treatment_Cost DESC
       ) AS Ranking
FROM report
)
SELECT *
FROM RankedPatients
WHERE Ranking<=3;

-- Write a query to calculate the average waiting time for each doctor and display only doctors whose average waiting time is greater than the overall average.
SELECT Doctor,
       AVG(Waiting_Time) AS Avg_Waiting_Time
FROM report
GROUP BY Doctor
HAVING AVG(Waiting_Time) >
(
SELECT AVG(Waiting_Time)
FROM report
);

-- Write a query to identify the highest revenue-generating department and calculate its percentage contribution to the total hospital revenue.
WITH Revenue AS
(
SELECT Department,
       SUM(Treatment_Cost) AS Revenue
FROM report
GROUP BY Department
)

SELECT Department,
       Revenue,
       ROUND((Revenue /
       (SELECT SUM(Treatment_Cost)
       FROM report))*100,2) AS Revenue_Percentage
FROM Revenue
ORDER BY Revenue DESC
LIMIT 1;







